### ISSUE TITLE
cfssl NewResponder requirement changes

### ISSUE THREAD

**Issue by dylanloi** [T-Systems-MMS/vault-ocsp#4]
Hi, 

In an attempt to build vault-ocsp, it was failing on go get:

```
$ go get
# _/vault-ocsp
./vault_ocsp.go:62:38: not enough arguments in call to "github.com/cloudflare/cfssl/ocsp".NewResponder
        have (*VaultSource)
        want ("github.com/cloudflare/cfssl/ocsp".Source, "github.com/cloudflare/cfssl/ocsp".Stats)
```

Looks like under cloudflare/cfssl/ocsp/responder.go, the NewResponder is looking for Source and Stats now:

```
// NewResponder instantiates a Responder with the give Source.
func NewResponder(source Source, stats Stats) *Responder {
        return &Responder{
                Source: source,
                stats:  stats,
                clk:    clock.New(),
        }
}
```

**Comment by goldstar611** [comment]
Looks like this would be a simple fix to add a `nil` parameter as seen in https://github.com/cloudflare/cfssl/blob/503b4d7bdf090b00d20d67dcc1d129163c86d5c7/cli/ocspserve/ocspserve.go#L54

**Comment by jandd** [comment]
@dylanloi thanks for the report
@goldstar611 thanks for the link

The interface change was a little bit more complex. I adapted the vault-ocsp code to match the new interface.
